// the layout file is used to wrap other files in the folder with the same styling or rules.
// this is the place where we specify the fonts, the wrappers like Clerk, etc.

import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] }); // this is the way of importing fonts in next.js

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Follow Clerk documentation. It has all the steps to configure clerk easily.
    <ClerkProvider
    >
      <html lang="en">
        <body className={`${inter.className} bg-dark-1 grid place-content-center min-h-screen`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
